### ISSUE TITLE
翻页功能的实现问题

### ISSUE THREAD

**Issue by kingkangyu** [rongcloud/sealclass-server#1]
文档有提到只有教师有翻页的功能，但是我部署了一下，现在助教，学生都有翻页的功能
并且即使老师翻页，学生和助教也不和老师联动翻页

**Comment by lifei444** [comment]
考虑到实际操作中，学生也能往回翻白板复习学过的内容，所以翻页联动功能取消了。
文档里还没有及时删除，我们会修改文档，去掉相关功能的描述。
多谢反馈！

**Comment by kingkangyu** [comment]
好的，谢谢。

**Comment by kingkangyu** [comment]
> 考虑到实际操作中，学生也能往回翻白板复习学过的内容，所以翻页联动功能取消了。
> 文档里还没有及时删除，我们会修改文档，去掉相关功能的描述。
> 多谢反馈！

能提供一下哪个版本支持联动翻页功能吗，我们这边的项目比较需要这个联动翻页的功能。

**Comment by lifei444** [comment]
这个功能之前的版本也没有提供。如果要做的话我这边只能简单提供下思路：
1. 老师翻页的时候给房间里所有人下发翻页消息
2. 房间里成员收到翻页消息时代码控制白板翻页
2. 房间里保存当前白板的页码，后进来的成员代码控制直接跳转到老师所在页

**Comment by kingkangyu** [comment]
> 这个功能之前的版本也没有提供。如果要做的话我这边只能简单提供下思路：
> 
> 1. 老师翻页的时候给房间里所有人下发翻页消息
> 2. 房间里成员收到翻页消息时代码控制白板翻页
> 3. 房间里保存当前白板的页码，后进来的成员代码控制直接跳转到老师所在页

好的，谢谢。
