### ISSUE TITLE
http://localhost:9999/api/v2/school/create 创建分校报异常

### ISSUE THREAD

**Issue by kingkangyu** [rongcloud/sealclass-server#2]
<img width="1519" alt="image" src="https://user-images.githubusercontent.com/3354625/79758990-afe71200-8350-11ea-95e7-05b6603a20e6.png">

更改哪里的设置，或者postman添加什么能避免这个问题？

**Comment by liusong1111** [comment]
代码里对所有api调用都检查request header，要求必须传入用于身份认证的token，所以报了这个错。

所以README里描述的创建学校的方法行不通。

https://github.com/rongcloud/sealclass-server/blob/v2.0/tools/sealclass-02.sql

这个sql会初始化一个学校，update相应的sid, name, appkey, secret就可以了。

希望维护者修改README
